version: '3.8'

services:
  frontend:
    build:
      context: ./task-manager-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./TaskManagerAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./TaskManagerAPI:/app
      - ./db:/app/db
